version: 1.0.{build}
image: Visual Studio 2017

clone_folder: c:\gopath\src\github.com\heyrizla\nwjs-ffmpeg

environment:
  GOPATH: c:\gopath
  APPVEYOR_RDP_PASSWORD:
    secure: DI3zbbexwSOr5cN2pC6q2A==

stack: go 1.10

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: >-
      pip install pywin32

build_script:
  - go build main.go
  - ps: .\main.exe

after_build:
  - cmd: >-
      7z a %APPVEYOR_BUILD_FOLDER%\dist\windows.zip %APPVEYOR_BUILD_FOLDER%\dist\artifacts\*

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: dist\windows.zip
