version: 1.0.{build}
image: Visual Studio 2017

clone_folder: c:\gopath\src\github.com\heyrizla\nwjs-ffmpeg

environment:
  GOPATH: c:\gopath

stack: go 1.10

install:
  - cmd: >-
      pip install pywin32

build_script:
  - go build main.go
  - ps: .\main.exe

after_build:
  - cmd: >-
      7z a %APPVEYOR_BUILD_FOLDER%\dist\windows.zip %APPVEYOR_BUILD_FOLDER%\dist\artifacts\*

artifacts:
  - path: dist\windows.zip
