version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/heyrizla/nwjs-ffmpeg
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install lsb-core file g++-arm-linux-gnueabihf
      - run: go build main.go
      - run: ./main

      - store_artifacts:
          path: dist/artifacts/
