name: CI

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Use GO 1.13
        uses: actions/setup-go@v1
        with:
          go-version: "1.13.6"
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          brew install opus yasm
      - name: build and run
        run: |
          go build main.go
          ./main
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: "macos"
          path: dist/artifacts
